id: P001706
initial_creation_type: ocr
source_metadata:
  id: bdr:W22166
  title: ཐེག་པ་སྤྱི་བཅིངས་རྩ་འགྲེལ
  author: ''
  volumes:
    5173c807b4ad4d56ba79117fa898c111:
      image_group_id: I4226
      title: ''
      volume_number: 1
      total_pages: 482
